# Generated by Django 2.2 on 2021-11-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('one', models.CharField(max_length=50)),
                ('two', models.CharField(max_length=50)),
                ('three', models.CharField(max_length=50)),
                ('one_count', models.IntegerField(default=0)),
                ('two_count', models.IntegerField(default=0)),
                ('three_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
